name = "GCATs"
mc_version = "1.21.5"

[jar]
type = "fabric"
loader = "0.16.14"
installer = "latest"

[variables]
SERVER_PORT = "25565"

[launcher]
eula_args = true
nogui = true

[markdown]
files = ["README.md"]
auto_update = false

# MARK: Simply Optimized
[[mods]]
type = "modrinth"
id = "g96Z4WVZ"
version = "flRkZbyf"

[[mods]]
type = "modrinth"
id = "5ZwdcRci"
version = "dk4uLLmV"

[[mods]]
type = "modrinth"
id = "qQyHxfxd"
version = "CHlHxkvf"

[[mods]]
type = "modrinth"
id = "Ps1zyz6x"
version = "UueJNiJn"

[[mods]]
type = "modrinth"
id = "VSNURh3q"
version = "OvXvTD3H"

[[mods]]
type = "modrinth"
id = "9s6osm5g"
version = "qA00xo1O"

[[mods]]
type = "modrinth"
id = "NNAgCjsB"
version = "29GV7fju"

[[mods]]
type = "modrinth"
id = "P7dR8mSH"
version = "w6P5mySo"

[[mods]]
type = "modrinth"
id = "uXXizFIs"
version = "CtMpt7Jr"

[[mods]]
type = "modrinth"
id = "gvQqBUqZ"
version = "VWYoZjBF"

[[mods]]
type = "modrinth"
id = "51shyZVL"
version = "MDkI6Huh"

[[mods]]
type = "modrinth"
id = "KuNKN7d2"
version = "sUh67T4Y"

[[mods]]
type = "modrinth"
id = "AANobbMI"
version = "DA250htH"

[[mods]]
type = "modrinth"
id = "vSEH1ERy"
version = "IvtlnXcT"

[[mods]]
type = "modrinth"
id = "wnEe9KBa"
version = "EKg6v67t"

# MARK: Server Tweaks
[[mods]]
type = "modrinth"
id = "too-fast"
version = "dYcSl7Ir"

[[mods]]
type = "modrinth"
id = "viafabric"
version = "2JihKmGc"

[[mods]]
type = "modrinth"
id = "tt20"
version = "MjGahcCF"

[[mods]]
type = "modrinth"
id = "no-chat-reports"
version = "CHlHxkvf"

# MARK: Libraries

[[mods]]
type = "modrinth"
id = "forge-config-api-port"
version = "mlQdrgSO"

[[mods]]
type = "modrinth"
id = "collective"
version = "aCWSF57s"

[[mods]]
type = "modrinth"
id = "cobweb"
version = "dGvgd002"

[[mods]]
type = "modrinth"
id = "balm"
version = "KHiNGdha"

# MARK: Worldgen
[[mods]]
type = "modrinth"
id = "geophilic"
version = "P4R9W6RV"

[[mods]]
type = "url"
url = "https://github.com/Crystalis7/Hybrid-Beta/releases/download/source-v1.0.4%2F1.21.5/cascades-source-v1.0.4-1.21.5.zip"
# FIXME: this directory escalation is probably undefined behavior in mcman
# ...but it works!
filename = "../world/datapacks/cascades-source-v1.0.4-1.21.5.zip"

[[mods]]
type = "modrinth"
id = "nullscape"
version = "4qC7kfiC"

# Fix stone on cliffs
[[mods]]
type = "modrinth"
id = "mc-258859"
version = "x688NRQ5"

[[mods]]
type = "modrinth"
id = "cliff-face"
version = "bG1RvM4K"


# MARK: Structures
[[mods]]
type = "modrinth"
id = "hopo-better-ruined-portals"
version = "evvyMtKE"

[[mods]]
type = "modrinth"
id = "wabi-sabi-structures"
version = "E4l1JSkp"

[[mods]]
type = "modrinth"
id = "formations-overworld"
version = "wBfHURmx"

[[mods]]
type = "modrinth"
id = "formations"
version = "1kcjaPDC"

[[mods]]
type = "modrinth"
id = "hopo-better-mineshaft"
version = "MCgkP4Rh"

[[mods]]
type = "modrinth"
id = "explorations"
version = "e3PQefJc"

# MARK: Admin Tools
[[mods]]
type = "modrinth"
id = "invview"
version = "VD8wa5Wp"

# MARK: Tweaks
[[mods]]
type = "modrinth"
id = "kleeslabs"
version = "GTkzTHuw"

[[mods]]
type = "modrinth"
id = "nodurability"
version = "tLtjbex2"

[[mods]]
type = "modrinth"
id = "no-hostiles-around-campfire"
version = "gH4BfZ8u"

[[mods]]
type = "modrinth"
id = "torch-hit"
version = "iZvbqo6T"

[[mods]]
type = "modrinth"
id = "tnt-breaks-bedrock"
version = "YOBYUBNe"

[[mods]]
type = "modrinth"
id = "lunas-keep-inventory"
version = "8A4t8eG2"


# MARK: Navigation
[[mods]]
type = "modrinth"
id = "just-atlas"
version = "eFzG3DU9"

[[mods]]
type = "modrinth"
id = "interdimensional-map-markers"
version = "eHNcLwUN"

[[mods]]
type = "modrinth"
id = "cheaper-maps"
version = "DMV9aGIr"

[[mods]]
type = "modrinth"
id = "fast-minecart"
version = "ctRpRL9K"

[[mods]]
type = "modrinth"
id = "no-firework-boosting"
version = "mrPn9id4"

[[mods]]
type = "modrinth"
id = "player-locator-bars"
version = "7Dz1dXjP"

# MARK: AFK
[[mods]]
type = "modrinth"
id = "detect-afk"
version = "XqCzI2eC"

[[mods]]
type = "modrinth"
id = "afk-dim-names"
version = "Ey6b0R3u"

[[mods]]
type = "modrinth"
id = "afk-sit"
version = "77SFXORJ"

# MARK: Head drops
[[mods]]
type = "modrinth"
id = "just-mob-heads"
version = "hbgvhaSJ"

[[mods]]
type = "modrinth"
id = "just-player-heads"
version = "kIVhv3YU"
