name: Export Packwiz

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.toml'
      - '**.json'
      - 'config/**'
      - 'datapacks/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  packwiz-export:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: [info]

    steps:
    - uses: actions/checkout@v2

    - name: Install mcman
      run: |
        sudo curl -L -o /usr/bin/mcman https://github.com/ParadigmMC/mcman/releases/latest/download/mcman
        sudo chmod +x /usr/bin/mcman

    - name: Run mcman export packwiz
      run: mcman export packwiz
      env:
        MODPACK_VERSION: ${{ needs.info.outputs.server_version }}

    - uses: stefanzweifel/git-auto-commit-action@v5
      if: ${{ github.event_name == 'pull_request' }}
      with:
        commit_message: Update packwiz pack

    - name: Create packwiz zip
      run: zip -r ${{ needs.info.outputs.server_name }}-${{ needs.info.outputs.server_version }}-packwiz.zip pack
    
    - name: Upload packwiz zip
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.info.outputs.server_version }}.packwiz
        path: ${{ needs.info.outputs.server_name }}-${{ needs.info.outputs.server_version }}-packwiz.zip

  mrpack-export:
    runs-on: ubuntu-latest
    
    needs: [info]

    steps:
    - uses: actions/checkout@v2

    - name: Install mcman
      run: |
        sudo curl -L -o /usr/bin/mcman https://github.com/ParadigmMC/mcman/releases/latest/download/mcman
        sudo chmod +x /usr/bin/mcman

    - name: Run mcman export mrpack
      run: mcman export mrpack
      env:
        MODPACK_VERSION: ${{ needs.info.outputs.server_version }}

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.info.outputs.server_version }}.mrpack
        path: ${{ needs.info.outputs.server_name }}-${{ needs.info.outputs.server_version }}.mrpack

  info:
    runs-on: ubuntu-latest

    outputs:
      server_name: ${{ steps.server_name.outputs.value }}
      server_version: ${{ steps.server_version.outputs.value }}
      make_release: ${{ steps.check_release.outputs.make_release }}

    steps:
      - uses: actions/checkout@v2

      - name: Get server name
        uses: SebRollen/toml-action@v1.2.0
        id: server_name
        with:
          file: 'server.toml'
          field: 'name'

      - name: Check server version
        uses: SebRollen/toml-action@v1.2.0
        id: check_server_version
        with:
          file: 'server.toml'
          field: 'server_version'
      
      - name: Get server version
        id: server_version
        run: echo "value=v${{ steps.check_server_version.outputs.value }}" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check_tag
        with:
          tag: ${{ steps.server_version.outputs.value }}

      - name: Check if new release should be generated
        id: check_release
        run: |
          echo "make_release=${{ steps.check_tag.outputs.exists == 'false' && github.ref_name == 'main' }}" >> $GITHUB_OUTPUT

  publish-release:
    runs-on: ubuntu-latest

    needs: [info, packwiz-export, mrpack-export]
    if: ${{ needs.info.outputs.make_release == 'true' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4

      - name: Check if required artifacts exist
        id: check_artifact
        shell: bash
        run: |
          if [ ! -f ${{ needs.info.outputs.server_version }}.packwiz ]; then
            echo '::error::No value found for artifact `${{ needs.info.outputs.server_version }}.packwiz`.' && exit 1
          fi

          if [ ! -f ${{ needs.info.outputs.server_version }}.mrpack ]; then
            echo '::error::No value found for artifact `${{ needs.info.outputs.server_version }}.mrpack`.' && exit 1
          fi

      - name: Publish release
        id: release
        uses: softprops/action-gh-release@v2.3.2
        with:
          name: ${{ needs.info.outputs.server_version }}
          tag_name: ${{ needs.info.outputs.server_version }}
          target_commitish: ${{ github.ref_name }}
          files: |
            ${{ needs.info.outputs.server_name }}-${{ needs.info.outputs.server_version }}-packwiz.zip
            ${{ needs.info.outputs.server_name }}-${{ needs.info.outputs.server_version }}.mrpack
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
